version: '3'
services:

  postgres:
    image: postgres:11.4
    container_name: Angular-Nest-Postgres-TypeORM
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

