version: '2.2'
services:

  crud-service:
    image: akka-dailis:0.0.1-SNAPSHOT
    container_name: akka-crud-dailiis
    mem_limit: 2g
    environment:
      APP_CONFIG_PATH: /opt/conf/application.conf
    volumes:
      - ./config/application.conf:/opt/conf/application.conf
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:11.4
    container_name: crud-service-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dailiis
      - POSTGRES_PASSWORD=daaiiliis
      - POSTGRES_DB=dailis